# Generated by Django 5.1.1 on 2024-09-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="create",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="user",
        ),
    ]
